name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: mehmet
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Change versions in files
      run: echo ${{github.run_number}}
