name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Change versions in files
      run: |
        set -e
        version_new="3.3."$((20+${{github.run_number}}))
        echo "$version_new" >> $GITHUB_ENV
        echo ${{secrets.TEST}}
        version=$(cat VERSION)
        echo $version
        sed -i -e 's/'$version'/'$version_new'/g' VERSION README.md
    - name: Git Tasks
      run: |
        git config user.name "mersancengiz"
        git config user.email ersan.cengiz@iyzico.com
        git add .
        git commit -m "Test commit"
        git push origin main
    - name: Github Release
      run: |
        echo "Creating GitHub release..."
        #create_asset_json=$(curl -# -XPOST -H "Authorization: token ${{secrets.TEST}}" -H "Content-Type: application/json" -H "Accept:application/json" --data-binary '{"tag_name": "v$version_new","target_commitish": "master","name": "iyzipay-java v$version_new","body": "version $version_new","draft": false,"prerelease": false}' https://api.github.com/repos/mersancengiz/test/releases)
        echo $create_asset_json
        echo $env.version_new
        #echo "GitHub release created!"
        #upload_url=$( echo $create_asset_json | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["upload_url"][0:obj["upload_url"].find("{")];' )
        #echo $upload_url
